name: Add Branch Protection Rules

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'The name of the repository to add branch protection'
        required: true

jobs:
  add-branch-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Add Branch Protection Rules
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
        run: |
          curl -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/${{ github.repository_owner }}/${{ github.event.inputs.repo_name }}/branches/main/protection \
          -d '{
            "required_status_checks": {
              "strict": true,
              "contexts": ["ci/test"]
            },
            "enforce_admins": true,
            "required_pull_request_reviews": {
              "required_approving_review_count": 2
            },
            "restrictions":null
          }'
