name: Set Branch Protection on New Repo

on:
  repository_dispatch:
    types: [created]

jobs:
  set-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch protection
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
        run: |
          import os
          import json
          from github import Github

          # Parse the event payload
          event_payload = json.loads(os.environ['GITHUB_EVENT_PATH'])
          new_repo_name = event_payload['repository']['name']

          g = Github(os.environ['GITHUB_TOKEN'])
          org = g.get_organization("OleksSyde")
          repo = org.get_repo(new_repo_name)

          branch = repo.get_branch("main")
          branch.edit_protection(
              required_approving_review_count=1,
              dismiss_stale_reviews=True,
              require_code_owner_reviews=True,
              enforce_admins=True,
              required_status_checks=None,
              restrictions=None
          )

          print(f"Branch protection set for {repo.name}")
